# Generated by Django 4.0.1 on 2022-05-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
                ('author_last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.author')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientfname', models.CharField(max_length=50)),
                ('clientlname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('caddress', models.CharField(max_length=100)),
                ('phonenumber', models.FloatField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('phonenumber', models.FloatField(max_length=11)),
                ('paddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=4)),
                ('qty', models.FloatField(max_length=4)),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.book')),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.client')),
            ],
        ),
        migrations.CreateModel(
            name='InStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=10)),
                ('qty', models.FloatField(max_length=4)),
                ('bookID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='board.book')),
                ('genreID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='board.genre')),
                ('publisherID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='board.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genreID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.publisher'),
        ),
    ]
